### ISSUE TITLE
Four machine-assigned terms in the Computer-Human Interfaces group

### ISSUE THREAD

**Issue by theareaorg** [theareaorg/AREA-Research-Agenda#10]
They are:
- "program assemblers," 
- "software tools," 
- "technology," and 
- "online front-ends."

Having the term "technology" doesn't feel right to me. 

Why isn't "software tools" a term in the "developers" group?

**Comment by wzbernstein** [comment]
Yes, I noticed this one.  
"software tools" should definitely not be in CHI.  I agree with moving it to Developers.

**Comment by theareaorg** [comment]
This machine-assigned term will be moved by Bill to Developers.

**Comment by wzbernstein** [comment]
moved "software tools" to Developers
