### ISSUE TITLE
How (on what basis) should the categories be listed?

### ISSUE THREAD

**Issue by theareaorg** [theareaorg/AREA-Research-Agenda#12]
This issue pertains to [this page](https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Categories_of_Research_Topic_Groups.adoc) 

The question is how the categories should be listed:
Priority (hahaha!)
Number of articles? 
Alphabetical?

**Comment by wzbernstein** [comment]
Interesting question.  Personally, I think it should be listed alphabetically.

**Comment by theareaorg** [comment]
Not having any preferences, I put them in alphabetical order.
