### ISSUE TITLE
Terminology on the About-Low-Level-Terms page and in all documentation

### ISSUE THREAD

**Issue by theareaorg** [theareaorg/AREA-Research-Agenda#2]
This issue pertains to [this page](https://github.com/theareaorg/AREA-Research-Agenda/blob/main/Documentation/About-Low-Level-Terms.adoc) and our choice of terms on this page and, by extension, throughout the documentation.

We have used "low-level" and "mid-level" to signify "machine-assigned" terms and terms to which we manually grouped the low-level terms, respectively. 

Do we want to choose different names for low-level and mid-level terms?

**Comment by cperey** [comment]
Categories = High Level Terms
Groups = Mid-Level Terms
Machine-assigned labels = Low-Level Terms

**Comment by bchap-erau** [comment]
This sounds fine for the paper. The FindAR interface does not yet use the high levels and "Groups" is somewhat vague in isolation.

**Comment by theareaorg** [comment]
The Research Agenda will use the terms proposed. In FindAR 

Categories are not used
Groups = Main Topics
Low-Level Terms= Terms
