### ISSUE TITLE
Links needed for Research Methodologies Page

### ISSUE THREAD

**Issue by j-derby** [theareaorg/AREA-Research-Agenda#32]
One of the suggestions that brought up during user testing regarding the "Research Methodologies" page was that users wanted to click on and be sent to websites where they could find more info about "AAPOR Best Practices Guidelines for survey research", "QRCA for qualitative research", and "HFES defining technical standards".

Does someone have the links to each of these best practices/standards so we can ask Sofya to add these to the site?

**Comment by peterorban** [comment]
Here you go:
"AAPOR Best Practices Guidelines for survey research", https://www.aapor.org/Standards-Ethics/Best-Practices.aspx
"QRCA for qualitative research", https://cdn.ymaws.com/www.qrca.org/resource/resmgr/imported/Guidelines1-29-07.pdf
"HFES defining technical standards" https://www.hfes.org/Publications/Technical-Standards
