### ISSUE TITLE
Test methods to estimate prior research on proposed topics

### ISSUE THREAD

**Issue by theareaorg** [theareaorg/AREA-Research-Agenda#33]
This issue is to provide to Bill a sample of research topics that are considered complete on which to run some tests. 

I recommend testing with these topics: 

1. https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Research_Topics/BIntegration5-sensorfusion.adoc

2. https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Research_Topics/Denergy5-DSPsforlowpower.adoc

3. https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Research_Topics/Ehumanfactors5-visualencoding.adoc

4. https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Research_Topics/Iemergency5-thermalvision.adoc

5. https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Research_Topics/Imetalsandmining5-Crewingnewvaluechain.adoc

6. https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Research_Topics/Iutilities5-digitalwater.adoc

7. https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Research_Topics/Sapis5-trackinglibraries.adoc

8. https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Research_Topics/Usafety5-hazardsinproximity.adoc

9. https://github.com/theareaorg/AREA-Research-Agenda/blob/main/AREA_Research_Agenda_2021/Categories_and_Topics/Research_Topics/Usafety5-riskcategorization.adoc

**Comment by wzbernstein** [comment]
great - thank you.  working on it now...
