### ISSUE TITLE
Assignments of three groups currently in "Technology" category need more study

### ISSUE THREAD

**Issue by theareaorg** [theareaorg/AREA-Research-Agenda#6]
I don’t recommend that we make these changes before the webinar, but I recommend that at some point we return to discussing these assignments in the Technology category:

1. Smart Cities (rename it to “Urban Management” or something like that?) and move from Technology to Industries or Use Cases

2. Telecommunications move from Technology to Industries

3. Simulation to be moved from Technology to Use Cases (using AR to simulate user's tasks or challenging environments)

**Comment by bchap-erau** [comment]
I agree that we could move to Use Cases but I like the term Smart Cities and think it will resonate with our users. 
I agree with moving Telecomm to Industries and Simulation to Use Cases.

**Comment by theareaorg** [comment]
Today we agreed and implemented these changes in New Low-Level Terms
