### ISSUE TITLE
HC Interfaces or CH Interactions? Which one and why not be consistent?

### ISSUE THREAD

**Issue by theareaorg** [theareaorg/AREA-Research-Agenda#7]
Within the End User and User Experience Category, we have Computer-Human Interfaces and Human-Computer Interactions as groups. How are these different and why don't we use one convention (on what basis)?

**Comment by theareaorg** [comment]
We agreed that Bill and/or Barb will combine all the five low-level terms in Computer-Human Interfaces and Human-Computer Interactions into one mid-level term (group) called "Human-Computer Interaction"

**Comment by bchap-erau** [comment]
Bill - I highlighted these on the "New Low Level Organized" tab in our bucket sheet.  We need to resolve the two 'online front end' terms.

**Comment by wzbernstein** [comment]
merged old groups into "human-computer interaction" | aliased "online front-end" to "online front end"
