### ISSUE TITLE
What to do about Business group name = Business category name?

### ISSUE THREAD

**Issue by theareaorg** [theareaorg/AREA-Research-Agenda#8]
Proposed solution: I suggest that one of us goes through all the macine-assigned terms currently assigned to the "business" group and reassign them to new group names that have more clear meanings, such as:
- measuring business metrics and performance (business data processing)
- human resources (employment and unemployment)
- process, resource and business planning
- financial tracking and planning (retail data, banking, expenses and investments), 
- advertising, marketing and sales (all forms of commerce, customer management and service) use cases

**Comment by theareaorg** [comment]
There are 112 machine-assigned terms in the business mid-level term. The extra work to manage additional groups is minimal. 

The mid-level terms we will have in this group will be:
- Integration
- Logistics
- Policy
- Business Performance Metrics
- Human Resources
- Business Planning 
- Sales and Marketing

**Comment by wzbernstein** [comment]
I will move ahead with the latest version (today) without these new groups.

**Comment by theareaorg** [comment]
I'm working on reassignment of the 112 machine assigned terms on the tab called "NEW LOW LEVEL ORGANIZED" of this [spreadsheet](https://docs.google.com/spreadsheets/d/1sfMGYRVAEJv5TeBcFTEW4Cqs0Tar_jE6/edit#gid=1833680787) 

Will comment when I'm finished with that process.

**Comment by theareaorg** [comment]
Note that we have 
small-to-medium enterprises and small to medium enterprises as two different low-level terms

**Comment by theareaorg** [comment]
I have finished the reassignment of the low-level terms. Please crunch the groups again!

When (Bill) you've completed this, please note that and close this issue.

Many thanks!

**Comment by wzbernstein** [comment]
integrated into data processing pipeline.
